# Generated by Django 4.2.7 on 2023-12-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygo_market_watch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=255)),
                ('print_tag', models.CharField(max_length=20)),
                ('rarity', models.CharField(max_length=50)),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('average_price', models.FloatField()),
                ('shift', models.FloatField()),
                ('shift_3', models.FloatField()),
                ('shift_7', models.FloatField()),
                ('shift_30', models.FloatField()),
                ('shift_90', models.FloatField()),
                ('shift_180', models.FloatField()),
                ('shift_365', models.FloatField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
