# Generated by Django 4.2.7 on 2023-12-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygo_market_watch', '0002_card_delete_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card',
            new_name='name_of_set',
        ),
        migrations.AddField(
            model_name='card',
            name='Card_name',
            field=models.CharField(default='Blue-Eyes White Dragon', max_length=255),
        ),
    ]
