# Generated by Django 4.2.7 on 2024-01-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygo_market_watch', '0003_rename_card_card_name_of_set_card_card_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_image',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images/'),
        ),
    ]
