# Generated by Django 4.2.7 on 2024-01-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygo_market_watch', '0004_card_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_image',
            field=models.ImageField(default='images/default_image.jpeg', upload_to='images/'),
        ),
    ]
