# Generated by Django 4.2.7 on 2024-01-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygo_market_watch', '0005_alter_card_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
