# Generated by Django 4.2.7 on 2024-03-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygo_market_watch', '0006_card_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='shift',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='card',
            name='shift_180',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='card',
            name='shift_3',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='card',
            name='shift_30',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='card',
            name='shift_365',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='card',
            name='shift_7',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='card',
            name='shift_90',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
